### ISSUE TITLE
Feature request: Add nix support 

### ISSUE THREAD

**Issue by vibrantleaf** [hyprgreen/main#1]
Not sure about this, nix looks like it might be a nice idea to add, but I have a few issues:

1. Nix wants to create a `/nix` dir which is impossible due to `/` being read-only, looks like there make be some workarounds.

see: https://julianhofer.eu/blog/01-silverblue-nix/

2. I have **zero** experience with nix or nixos.

**Comment by howyay** [comment]
Determinate Systems have created a wonderful project that allows a fairly smooth experience installing Nix on OSTree distributions at [DeterminateSystems/nix-installer](https://github.com/DeterminateSystems/nix-installer).

I've been using it with home-manager since OSTree support was initially added with no instability or end-user compromises, and I will certainly vouch for the possibility of integration.
